services:
  - type: static
    name: resq-frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: NODE_VERSION
        value: 18.18.0 # Explicitly set to a supported version
      - key: PORT
        value: 10000 