services:
  - type: web
    name: resq-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 18.18.0 # Explicitly set to a supported version 